### ISSUE TITLE
Main Page - Slider

### ISSUE THREAD

**Issue by jindonyy** [Co-Studo/Co-Studo-front#17]
## 예상 동작
메인 페이지 스터디 카드가 4개 이상일 경우 슬라이드된다.

## 기능
- prev/next 버튼을 누르면 이전/다음 슬라이드로 넘어간다.
- headless, design system component
- option
  - [x] slidesToShow
  - [x] slidesToScroll
  - [x] arrows
  - [x] initialSlide
  - [x] speed
  - [x] slidesMargin
- default option
  - slidesToShow: 1
  - slidesToSlide: 1
  - arrows: true
  - initialSlide: 0
  - speed: 1000
  - slidesMargin: '0px'

**Comment by healtheloper** [comment]
issue close 는 PR 본문에 에 close #이슈번호 를 통해 merge 하면서 해주세용
